services:
  nginx:
    container_name: todoNginx
    platform: linux/x86_64
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../laravel:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - to-do-network
  laravel:
    container_name: todoLar
    working_dir: /var/www/html
    build:
      args:
        USER: www-data
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../laravel:/var/www/html
      - ./laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - to-do-network
  database:
    container_name: todoDB
    image: mysql:latest
    restart: unless-stopped
    command: --init-file /data/application/init.sql
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: 123test321
      MYSQL_ROOT_PASSWORD: 123test321
    volumes:
      - ./mysql/init_db.sql:/data/application/init.sql
    networks:
      - to-do-network
  phpmyadmin:
    container_name: todoPMA
    image: phpmyadmin
    ports:
      - "1500:80"
    environment:
      - PMA_HOSTS=database
    networks:
      - to-do-network
    depends_on:
      - database
  maildev:
    container_name: todoMaildev
    image: maildev/maildev
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - to-do-network
  redis:
    container_name: todoRedis
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - to-do-network
  node:
    container_name: todoNode
    build:
      context: ../
      dockerfile: tododocker/Dockerfile.node
    working_dir: /var/www/node
    volumes:
      - ../node:/var/www/node
      - /var/www/node/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - to-do-network
networks:
  to-do-network:
    driver: bridge

volumes:
  redis-data: